version: '3.0'

services:
  nginx:
    image: armdocker.rnd.ericsson.se/proj_openstack_tooling/amt_nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - express
    volumes:
      - ./config/sslcerts:/etc/nginx/certs

  filebeat:
    image: armdocker.rnd.ericsson.se/proj_openstack_tooling/amt_filebeat:latest
    volumes:
      - "/docker/containers:/usr/share/dockerlogs/data:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
       - logstash

  logstash:
    image: armdocker.rnd.ericsson.se/proj_openstack_tooling/amt_logstash:latest
    ports:
      - 5044:5044
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}

  express:
    image: armdocker.rnd.ericsson.se/proj_openstack_tooling/amt_server:latest
    restart: on-failure
    environment:
      - NODE_ENV=PROD
      - KEYCLOAK_USER=${KC_ADMIN_USERNAME}
      - KEYCLOAK_PASSWORD=${KC_ADMIN_PASSWORD}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - BB_FUNCTIONAL_USER=bbfuncuser
      - BB_FUNCTIONAL_USER_PASSWORD
      - PYTHON_PASSWORD=${PYTHON_PASSWORD}
    links:
      - database

  database:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/mongo:4.2.2
    ports:
      - "27017:27017"

  python:
    image: armdocker.rnd.ericsson.se/proj_openstack_tooling/amt_python:latest

  # mongoExporter:
  #   image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/targetprocess/mongodb_exporter:v0.1.0
  #   environment:
  #     - MONGODB_URL=mongodb://database:27017
  #   links:
  #     - database

  nodeExporter:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/prom/node-exporter:v0.17.0

  nginxExporter:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/nginx/nginx-prometheus-exporter:0.2.0
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
    ports:
      - "9113:9113"
    links:
      - nginx

  cAdvisor:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/google/cadvisor:v0.32.0
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
