version: '3.0'

services:
  nginx:
    build: services/nginx
    ports:
      - "80:80"
    depends_on:
      - express

  filebeat:
    build: services/filebeat
    volumes:
      - "/docker/containers:/usr/share/dockerlogs/data:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
       - logstash

  logstash:
    build:
      context: services/logstash
    ports:
      - 5044:5044
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}

  express:
    build: services/express
    restart: on-failure
    environment:
      - NODE_ENV=DEV
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - BB_FUNCTIONAL_USER=bbfuncuser
      - BB_FUNCTIONAL_USER_PASSWORD
      - PYTHON_PASSWORD=password
    links:
      - database
      - python

  database:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/mongo:4.2.2
    ports:
      - "27017:27017"

  python:
    build: services/python

  nodeExporter:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/prom/node-exporter:v0.17.0

  nginxExporter:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/nginx/nginx-prometheus-exporter:0.2.0
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
    ports:
      - "9113:9113"
    links:
      - nginx

  cAdvisor:
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/google/cadvisor:v0.32.0
